spf13/afero

README.md, fs_test.go, memfile.go, memmap.go
fixes #7 
I first had to fix registerWithParent(), unRegisterWithParent() and findParent() to correctly use the MemDir of the parent directory. Then I added versions of Open() and Mkdir() that don't acquire a lock, that they can be used atomically during Create() and Mkdir(). 
Finally I changed the output of the InMemoryFileInfo.Name() and Readdirnames() functions to only return the last element of the path, as does the os package.
I also added some tests.
=> fix Readdir() and Readdirnames()

fs_test.go, memmap.go
Rename did not change the name that is saved in the InMemoryFile and also didn't change the name that is saved in the parents MemDir. I added a Test to look out for such errors in the future.
=> Fix MemMapFs.Rename()

memfile.go
fix https://github.com/spf13/hugo/issues/1621
=> atomic requires struct field to be 64-bit aligned

afero_test.go, path_test.go
A few things are fixed by this commit:
- check error value returned from `fs.RemoveAll` in `removeAllTestFiles`.
- Defer statements are a LIFO, and were out of order in some test functions.
- The TestReaddir* funcs were failing to close some file handles.
- `findNames` was opening file handles but ignoring them.  Bad.
Closes #35
=> Fix closing and deleting of files in tests

mem/dir.go, mem/dirmap.go, mem/file.go, memmap.go, memmap_test.go
`mem.File` is split up into `mem.File` which is the file handle and `mem.FileData` that holds all the relevant data.
Fixes #54
=> Seperate MemMapFs file data and file handles

README.md, sftp.go, sftp/file.go, sftp_test.go
As discussed in #47, have fun :-)
=> Add SftpFs beta backend

const_darwin_openbsd.go, const_win_unix.go
Possibly other BSDs are affected as well but this fixed the build of the whole hugo package for me.
=> Fix OpenBSD build

const_bsds.go, const_win_unix.go
Solve this: https://github.com/spf13/afero/issues/68
go get github.com/spf13/afero
gocode/src/github.com/spf13/afero/const_win_unix.go:22: undefined: syscall.EBADFD
=> Fix syscall.EBADFD at FreeBSD

basepath.go, basepath_test.go
A common mistake in using the BasePathFs is to give it a real
OS absolute file path instead of a virtual one relative to the virtual base.
This commit adds some tests and returns an error on Windows in this case.
On Unix we have to train the users to do a better job.
See https://github.com/spf13/hugo/issues/1800
=> Improve absolute file paths handling in BasePathFs

basepath.go, basepath_test.go
Added fix to support "nested" `BasePathFs`. Unit-tests are also included.
=> Closes spf13/afero#79

basepath.go, basepath_test.go
Revert the previous `fullPath` changes and add tests for "nested" `BasePath`'s
=> Revert previous fullPath changes - add tests for nested BasePaths

copyOnWriteFs_test.go
my solution was trivial, but I left it out so the error can be replicated first.
```
dir := filepath.Dir(name)
var isaDir bool
if isaDir, err = IsDir(u.base, dir); os.IsNotExist(err) {
// skip ahead
} else if err != nil {
return nil, err
}
if isaDir {
if err = u.layer.MkdirAll(dir, 0777); err != nil {
return nil, err
}
return u.layer.OpenFile(name, flag, perm)
}  
```
=> test to replicate stat error

basepath_test.go, util.go, util_test.go
This method resolves the "Full" path of the `BasePathFs`. It also resolves for nested BasePaths.
Unit tests were also added
=> Add `FullBaseFsPath` utility method

README.md
Hi there,
I found some small typos in the testing example on the README. The calls to `WriteFile()` should follow the conventions as shown in the utility functions section in the README, instead of being called directly on the appFS variable (as it does not have a `WriteFile()` method).
Let me know if I'm just not understanding the example correctly, as that is entirely possible. :)
=> Fixed utility function calls in testing example

mem/file.go
For example, as seen in : https://travis-ci.org/google/mtail/jobs/153781970
=> Fixes a data race caused by not locking the mem.FileData for read access.

afero.go
I wasn't sure if I should remove the `all` or the `any`. Opted for `all` because of other use cases.
=> fixes typo in RemoveAll code comment

memmap.go, memmap_test.go
With MemMapFS the perm parameter is ignored with OpenFile, MkDir and MkDirAll
Tests added and run successfully.
Addresses Issue #107
=> Set perm in MemMapFS after OpenFile, MkDir and MkDirAll methods called

memmap.go, memmap_test.go
Concurrent modifications of the file system while calling
ReadDir was causing data races and sometimes panics.
=> Fix data races in MemMapFs

match.go, match_test.go
I needed the [`Glob`](https://golang.org/pkg/path/filepath/#Glob) functionality that Golang supports in their `path/filepath` package. I suppose someone else could use this, perhaps.
=> Added glob/match support to afero

.travis.yml, appveyor.yml, mem/file.go, mem/file_test.go
* Splitting SetModeTime to avoid double locking
* Adding locks all over the place.
Potential fix for #133
=> mem/file.go - Fix some races in accessing fields of FileData

cacheOnReadFs.go, composite_test.go
CacheOnReadFS erroneously returns a NotExists error even if the file is available in the base FS. This first commit demonstrates this error with a test. The following will include a fix.
=> CacheOnReadFS: erroneous NotExists error from MemMapFS layer

README.md
AppFs type is inferred from afero.NewOsFs(), go lint tools are complaining about expliciting the type.
> should omit type afero.Fs from declaration of var AppFs; it will be inferred from the right-hand side (golint)
=> readme: remove inferred type from AppFs declaration.

.travis.yml
Travis builds are failing on go 1.7.5 because of github.com/pkg/sftp doesn't support that version anymore.
=> Removes go 1.7 from the build matrix, adds 1.9

basepath.go, basepath_test.go
Files returned by the BasePathFs operations don't report a usable name (using `file.Name()`) since they include the prefix, which is prepended a second time by the Fs when passed back. For instance, the following doesn't work:
```go
osfs := afero.NewOsFs()
bfs := afero.NewBasePathFs(osfs, "/some/base/path")
f, _ := bfs.Create("relative/path")
// do some stuff
// This doesn't work since it tries to remove 
// /some/base/path/some/base/path/relative/path
bfs.Remove(f.Name())
```
This is especially irksome when working with TempFiles; basically anything that uses `file.Name()` ends up needing a type switch to get a path usable by the `Fs` object, which breaks the transparency of the Fs abstraction.
I've implemented a simple fix for this: add a `BasePathFile` type with an overridden `Name` …
=> fix File.Name() on BasePathFS (wrap File objects returned by BasePathFs)

basepath.go, basepath_test.go, cacheOnReadFs.go, composite_test.go, copyOnWriteFs.go, copyOnWriteFs_test.go, lstater.go, lstater_test.go, match.go, os.go, path.go, readonlyfs.go, unionFile.go
The interface has one method returning the `FileInfo` and a flag telling if `Lstat` was called or not.
```go
type Lstater interface {
LstatIfPossible(name string) (os.FileInfo, bool, error)
}
```
`Lstat` is currently only supported by the `OsFs`, but since that `Fs` can be used in others, they will also support it by proxy.
But not always, so hence this optional interface.
The interface is in this commit implemented for:
* BasePathFs
* OsFs
* CopyOnWriteFs
* ReadOnlyFs
Fixes #75
=> WORK IN PROGRESS: Add an optional Lstater interface

afero_test.go, mem/file.go
=> Return error in Readdir on regular mem file

composite_test.go, unionFile.go
Update Readdir to match behavior of stdlib os package.
Fixes #197
=> Fix UnionFile.Readdir return when c <= 0

mem/file.go, mem/file_test.go
This PR demonstrates a deviation from the `io.ReaderAt` API contract in the mem.File implementation.
> If ReadAt is reading from an input source with a seek offset, ReadAt should not affect nor be affected by the underlying seek offset.
https://github.com/spf13/afero/blob/d40851caa0d747393da1ffb28f7f9d8b4eeffebd/mem/file.go#L195
The PR modifies the mem.File impl to respect the contract by storing the original offset before the Read and restoring the offset after the Read.
=> add ReadAt/Seek test

README.md
New users coming to the project could incorrectly assume that the project is pre-1.0 release and that it hasn't had a release in years if they assumed that the release notes in the README were up-to-date. I say this because I assumed that on my first read.
=> Remove stale release notes from README

sftpfs/sftp_test.go
This fixes the disabled test with latest API from the sftp package. It is still not a very clean test but it works.
=> sftpfs: Fix test with latest API of the sftp package

mem/file.go
=> Return closed error in mem.File.Write() after Close()

sftpfs/sftp.go
Before, the OpenFile method was unimplemented, and just returned `nil,
nil`. Because the Afero.TempFile method calls the OpenFile method, this
behavior caused a nil pointer exception when TempFile was used with
sftpfs.
This commit adds a simple implementation for sftpfs.OpenFile, fixing the
exception thrown when using it with TempFile.
=> sftpfs: Implement OpenFile method

zipfs/file.go
If count == 0 all files should be returned like in https://golang.org/pkg/os/#File.Readdir
=> Fix zipfs.Readdir and zipfs.Readdirnames

basepath.go, copyOnWriteFs.go, os.go, readonlyfs.go, symlink.go, symlink_test.go
I created two interfaces to facilitate file systems optionally supporting the Symlink and Readlink operations from the os implementation.
```
type Linker interface {
SymlinkIfPossible(oldname, newname string) error
}
type LinkReader interface {
ReadlinkIfPossible(name string) (string, error)
}
```
I opted to write them this way to preserve consistency with the Lstater interface created by @bep 
The actual Symlink and Readlink are only implemented in the `OsFs`, with proxy support in:
- BasePathFs,
- CopyOnWriteFs, and
- ReadOnlyFs
for consistency with the other two I implemented the Linker interface on `ReadOnlyFs` with it just returning a not supported error. I would appreciate feedback if this is the correct pattern, or if I should instead remove the method?
The motivation for this …
=> Add optional interfaces for Symlink and Readlink

memmap.go, memmap_test.go
=> Add support for os.O_EXCL in afero.MemMapFs

memmap.go, memmap_test.go
I ran into an issue where my program called `fs.Chmod` and it changed from a directory to a regular file. This one had me stumped for weeks 😅 
After checking [`os.Chmod`'s docs](https://golang.org/pkg/os/#Chmod), I bit-masked the part Chmod is permitted to set, then OR'd it with the file's other previous mode bits. I also added a test to check the file type after setting all permission bits to 0.
=> Prevent MemMapFs.Chmod from changing all mode bits

memmap.go, memmap_test.go
- "/" should have mode `os.ModeDir|0755`, not `0000`. Among other things, this had resulted in `mode.IsDir()` returning false for root prior to this patch.
- `Mkdir`, `MkdirAll`, and `OpenFile` shouldn't be allowed to set permissions that are otherwise illegal through `Chmod`. This mirrors what Go's `os` package does: it calls `syscallMode(mode)`, which effectively clears out the same bits that are disallowed by `Chmod`.
- `MkdirAll` should use the given permissions for all intermediate directories that are created, not just for the final directory. Prior to this patch, intermediate directories were created with mode bits `0000`. Besides the permission bits being wrong, `mode.IsDir()` would return false for these directories prior to this patch.
A potentially amusing side note: I was …
=> Improve handling of mode bits

mem/file.go, mem/file_test.go
Hello, everyone,
Recently I needed an in-memory implementation of io.WriteSeeker and tried to use File. Unfortunately, my code panicked using afero's File implementation whereas os.File implementation worked flawlessly.
It looks like Write incorrectly sets offset after appending data. I've written a test for correct behaviour and implemented a fix.
Also, I check `whence` value in Seek against `io.Seek*` literals so it reads easier for people with bad memory like me.
=> mem: fix incorrect offset in Write

composite_test.go, unionFile.go
To match behavior of `os.File.Readdir`, argument c in `UnionFile.Readdir` should control amount of files read, not the upper bound of buffered files.
Fixes #259
=> Fix amount of files read in UnionFile.Readdir

go.mod, memmap.go, memmap_test.go
MemMapFs does not currently implement Lstater which can make it a bit difficult when a program is wanting to call Lstat on an unknown filesystem, so I am implementing the interface. The real call is to `Stat()`, and a `false` is simply returned to indicate that an Lstat was not called.
This change was prompted in my work of https://github.com/chigopher/pathlib, specifically: https://github.com/chigopher/pathlib/pull/16. The issue arose when testing a Walk function that calls LstatIfPossible, where the test uses a MemMapFs.
=> Make MemMapFs implement Lstater

tarfs/fs.go, tarfs/tarfs_test.go
Corrects a bug where passing an empty tar reader to tarfs would cause
adding the pseudoroot to panic with assignment to entry in nil map.
Signed-off-by: hasheddan <georgedanielmangum@gmail.com>
cc @agimenez because it looked like you implemented tarfs (thank you for your work!)
@kargakis would it be possible to get a v1.4.1 published after merge?
=> Do not panic on passing empty tar reader to tarfs

.travis.yml
Added power support for the travis.yml file with ppc64le. This is part of the Ubuntu distribution for ppc64le. This helps us simplify testing later when distributions are re-building and re-releasing
=> Added power support for the travis.yml file with ppc64le.

cacheOnReadFs.go, unionFile.go
This closes #193 by calling `OpenFile` instead of `Open` when appropiate, thus passing i.e. `O_CREATE` to the layer. Already tested in https://github.com/pojntfx/stfs.
=> Call `OpenFile` instead of `Open` in `CacheOnReadFs` (fixes #193)

mem/file.go, memmap_test.go
`NewOsFs` behaviour for `CreateDir` includes modTime on both Mac + Linux. 
`NewOsFs` behaviour for renaming directories does not update modTime.
This makes `NewMemMapFs` have the same behaviour rather than a time of `0001-01-01 00:00:00 +0000 UTC`
=> add modTime on folder creation

gcsfs/file.go, gcsfs/fs.go, gcsfs/gcs_test.go
`RemoveAll` in `gcsfs` returns an error when the file/directory to be removed doesn't exist. It should return nil in this case.
=> Fix gcsfs RemoveAll

memmap.go
when i RemoveAll lib directory, it also Removed libs directory
=> bugfix: RemoveAll

go.mod, go.sum
As explained in https://github.com/spf13/afero/pull/291#issuecomment-807324649, now that
`afero` supports `io/fs.FS`, it requires `go` >= `1.15.10`.
Rather than pinning to `1.15` and occasionally confusing users who are
on < `1.15.10`, I thought simplest to jump straight to `1.16`.
Especially given `1.18` was just released, the upstream `go` team no
longer even supports `1.15`.
The change to `go.sum` was the result of running `go mod tidy`.
=> Update `go.mod` to reflect that `afero` requires `go` >= `1.15.10`

.github/workflows/test.yml, const_bsds.go, const_win_unix.go, iofs.go, iofs_test.go
- all: Run gofmt -s -w
- Fix test failures on Windows
=> Misc build/test fixes

basepath.go, iofs.go, iofs_test.go
And implement `fs.ReadDirFile` for `BasePathFile`.
There are other `File` implementations that could also benefit from the above, but
this is a start.
The primary motivation behind this is to allow `fs.WalkDir` use the native
implementation whenever possible, as that new function was added in Go 1.16 with
speed as its main selling point.
This commit also adds a benchmark for `fs.WalkDir` that, when compared to the main branch:
```bash
name        old time/op    new time/op    delta
WalkDir-10     369µs ± 1%     196µs ± 3%  -46.89%  (p=0.029 n=4+4)
name        old alloc/op   new alloc/op   delta
WalkDir-10    85.3kB ± 0%    40.2kB ± 0%  -52.87%  (p=0.029 n=4+4)
name        old allocs/op  new allocs/op  delta
WalkDir-10       826 ± 0%       584 ± 0%  -29.30%  (p=0.029 n=4+4)
```
Fixes #365
=> Make IOFS.ReadDir check for fs.ReadDirFile

iofs.go, iofs_test.go, ioutil.go
We recently added a check for fs.ReadDirFile in IOFS.ReadDir, but forgot to apply a sort to the
result as defined in the spec.
This fixes that and adds a test case for it.
=> Fix sorting in IOFS.ReadDir

memmap.go, memmap_test.go
* The backing map is protected by a RWMutex
* This commit double checks for the existence of the directory inside the write lock to avoid potential data races when multiple goroutines tries to create
the same directory.
Fixes #361
Fixes #298
=> Fix concurrency issue in MemMapFs.Mkdir/MkdirAll

memmap.go, memmap_test.go
I think it should fix issue #141
=> Fix renaming a dir with sub-directories

sftpfs/file.go
This method is still a TODO after 6 years despite being a simple delegate, i don't think i missed any real reason why it wasn't implemented but i could be wrong.
=> Add sftpfs files ReadAt method

const_bsds.go, const_win_unix.go
Added flags to `const_bsds.go` and `const_win_unix.go` to allow for building on IBM z/OS Unix System Services.
Can now clone the afero repository on a z/OS USS shell and run `go install` with no issues.
Afero is a dependency for the k6 tool, and enabling these build flags allows k6 to be built and run on z/OS.
=> Add build flags for z/OS Unix System Services

gcsfs/errors.go, gcsfs/file_info.go, gcsfs/gcs_mocks.go
=> fix(gcsfs): update object not exist check logic
